In [1]:
import numpy as np

In [2]:
# Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
# operations like:
array1=np.array([10,20,30,40,50])

# a) Addition of 2 in all the element
print(array1+2)

# b) Multiply 3 with all the elements
print(array1*3)

# c) Divide every element by 2
print(array1/2)

[12 22 32 42 52]
[ 30  60  90 120 150]
[ 5. 10. 15. 20. 25.]


In [3]:
# Q.2 Questions on Basic NumPy Array:
array2=np.array([11,22,33,66,44,55])

# a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
array2=array2[::-1]
print(f"reversed array : {array2}" )
# b) Find the most frequent value and their indice(s) in the following arrays:
from statistics import mode
# i. x = np.array([1,2,3,4,5,1,2,1,1,1])
x = np.array([1,2,3,4,5,1,2,1,1,1])
mode1=mode(x)
x1=np.where(x==mode1)[0]
print(f"the mode of {x} is {mode1} and indices : {x1}")

# ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
mode2=mode(y)
y1=np.where(y==mode2)[0]
print(f"the mode of {y} is {mode2} and indices : {y1}")
     

reversed array : [55 44 66 33 22 11]
the mode of [1 2 3 4 5 1 2 1 1 1] is 1 and indices : [0 5 7 8 9]
the mode of [1 1 1 2 3 4 2 4 3 3] is 1 and indices : [0 1 2]


In [4]:
# Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
# elements using row and column indices as follows:
array3=np.array([[10,20,30],[40,50,60],[70,80,90]])
# a) Access 1st row, 2nd column
print(array3[0,1])
# b) Access 3rd row, 1st column
print(array3[2,0])

20
70


In [5]:
# Q.4 Write program to create an 1-D NumPy array named <> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
# shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same
# with T attribute?

krishna=np.linspace(10,100,25)
print(f"array is : {krishna}\n")
print(f"dimension : {krishna.ndim}")
print(f"shape : {krishna.shape}")
print(f"size : {krishna.size}")
print(f"dtype : {krishna.dtype}")
print(f"nbytes : {krishna.nbytes}\n")

t1=krishna.reshape(25,1)
print(f"transpose : {t1}\n")

t2=krishna.T
print(t2)

array is : [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

dimension : 1
shape : (25,)
size : 25
dtype : float64
nbytes : 200

transpose : [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [6]:
# Q5. Create a 2-D Array of three rows and four columns, named ucs420_> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
# median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_>. Resize the array to two rows and three
# columns and name it as resized_ ucs420_>.
ucs420=np.array([10,20,30,40,50,60,70,80,90,15,20,35])
ucs420=ucs420.reshape(3,4)
print(f"array is : \n{ucs420}\n")

mean=np.mean(ucs420)
median=np.median(ucs420)
max=np.max(ucs420)
min=np.min(ucs420)
uniqueElems=np.unique(ucs420)

print(f"mean : {mean}")
print(f"median : {median}")
print(f"max : {max}")
print(f"min : {min}")
print(f"unique : {uniqueElems}\n")

arr=ucs420.reshape(4,3)
print(arr,"\n")

arr1=np.resize(ucs420, (2, 3))
print(arr1)
     

array is : 
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

mean : 43.333333333333336
median : 37.5
max : 90
min : 10
unique : [10 15 20 30 35 40 50 60 70 80 90]

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]] 

[[10 20 30]
 [40 50 60]]
